puts "Los operadores de comparación nos van a servir para poder evaluar cuál es la similitud o diferencia entre dos objetos el lenguaje"
puts ""
puts "(>) éste operador es el de MAYOR QUE, que devuelve true or false dependiendo del resultado entre el valor de la izq y el de la derecha."
puts ""
puts "Ejecuta irb en la consola y prueba algunos ejemplos para descubrir los resultados."
puts ""
puts "El inverso seria (<) el MENOR QUE"
puts ""
puts "<= MENOR O IGUAL"
puts ""
puts ">= MAYOR O IGUAL"
puts ""
puts "<=> Operador de comparación COMBINADO, devuelve 3 posibles valores, en en caso de ser iguales devulve CERO, en el caso de que el primero sea mayor que el segundo devuelve 1, y el en caso del que el segundo sea mayor que el primero devuelve -1"
puts ""
puts "== IGUALDAD, que devuelve única y esclusivamente cuando ambos elementos son iguales"
puts ""
puts "Atentos a que el resultado con un == puede arrojarnos true pero debemos tener en cuenta el tipo de datos comparados, por ejemplo integer y floats lo cual indica que son de tipos distintos."
puts ""
puts "Cuando queremos comparar que tengan el mismo tipo utilizamos a.eql?(b) cuando igualamos a==b. eql? compara que sean del mismo valor y que además sean del mismo tipo."
puts ""
puts "Si comparamos strings como hola==hola escritos con comillas como debe ser, el valor y el tipo es el mismo, respetando las mayúsculas en las palabras. Deben de coomparar la escritura en caso de ser strings"
puts ""
puts "equal? para hola como string, sabemos que son del mismo tipo y valor. La diferencia aquí esta en el object.id de cada objeto. Para determinar el object.id de cada uno, lo ejecutamos como método al número o string según corresponda y arrojara object.id distintos."
puts ""
puts "Entonces equal? sirve para determinar si un elemento es copia de otro, porque si con copias conservan el mismo objetc.id, o más bie si el segundo objeto es la misma referencia que el primer objeto."
puts ""
puts "Por último != que devuelve false cuando son iguales, y true con no lo son."
